services:
  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j-data:/data
    environment:
        - NEO4J_AUTH
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  postgres:
    image: postgres:18
    volumes:
      - postgres-volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=as1db
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432
      - BIND_ADDRESS=0.0.0.0:3000
    ports:
      - "3000:3000"
    command: "as1db"
    depends_on:
      postgres:
        condition: service_started
    restart: always
    profiles:
      - backend

volumes:
  neo4j-data:
  postgres-volume:
